### ISSUE TITLE
Support convergence

### ISSUE THREAD

**Issue by Pharaone** [milikhin/seabass#1]
Awesome app!! Please support the other architectures (i386 and amd64) for support Ubuntu convergence! Thanks for this app!

**Comment by milikhin** [comment]
Thank you for your feedback.
Convergence is definetely among the project's goals.
For now I make amd64 builds for testing, but I think they need some additional work to achieve better UX - this is on my ToDo list, although not for the nearest releases.

I've also added current amd64 build to "Release" page.

**Comment by milikhin** [comment]
The app now can be installed on i386 and amd64 as Chrome/Chromium extension.
The package for ChromeOS is published in Chrome webstore.
The package for testing on other operating systems will be prepared for the next release.
