### ISSUE TITLE
Feature reaquest: Touch-highlight copy+paste

### ISSUE THREAD

**Issue by Funmungus** [milikhin/seabass#10]
Request the ability to highlight with a long-touch to highlight and copy+paste. Currently ctrl+c ctrl+a and ctrl+v work as keyboard shortcuts.  This feature request is especially targetted for virtual keyboard mode.

Key features:
1) Long touch to highlight a word block
2) A bar at each side of current highlight which can be dragged to change the highlighted area.
3) A popup with three buttons, copy, paste, and select all.  This popup should not be visible while dragging the highlight edges.

Refer to Ubuntu Touch UI for long press to highlight.

**Comment by milikhin** [comment]
Thank you for the ideas!
I'll see what i can do within Cordova framework and Ace editor for the next release

**Comment by Funmungus** [comment]
I am glad to help.
I just remembered cut also.  In my opinion not necessary, but it might be nice for some.

**Comment by milikhin** [comment]
It seems to be a bug in Cordova for Ubuntu. Touch selection/copy+paste works fine in browser, but doesn't work inside Cordova's webview. So, I'll fill bug report there.

It also seems that Cordova/HTML5 SDK for Ubuntu is not actively developed.

**Comment by milikhin** [comment]
Fixed in v0.4.8
