### ISSUE TITLE
App with unrestricted access in the Open Store.

### ISSUE THREAD

**Issue by Kliklink** [milikhin/seabass#4]
It would be great if you publish the version with unrestricted access in the Open Store (open.uappexplorer.com). This makes updating a lot easier.

**Comment by milikhin** [comment]
There are few issues remaining (with documentation, app building process and versioning) that I want to resolve before publishing unconfined version. 

I think everything will be ready till the 0.2.4 release and it'll be submitted to the Open Store.

**Comment by Kliklink** [comment]
Awesome :D

**Comment by milikhin** [comment]
There were few annoying bugs in last releases, now as they seems resolved, everything is ready for Open Store in next release.

**Comment by Kliklink** [comment]
Great, thank you :)

**Comment by milikhin** [comment]
done :)

**Comment by Kliklink** [comment]
Thank you ;)
