### ISSUE TITLE
Support highlighting other syntaxes

### ISSUE THREAD

**Issue by joaofl** [milikhin/seabass#5]
Would be nice to have an easy way to add support to other syntaxes. In my case i'm interested on  Latex syntax, for documents writing.

Other ideas:
- an explicit option to auto-save or not, with a save button.
- Option to change the background color of the editor
- option to minimize the navigation-tree bar
- option to reload the last document loaded

Hope it helps. Congrats for the initiative! It is the best app available for such.

**Comment by milikhin** [comment]
Thank you!

Latex support will be added in next release.
For now the easiest way to add support for other syntaxes is to open issues here, and if Ace editor supports required language ([over 120 supported languages for now](https://github.com/ajaxorg/ace#features)), it'll be added in the following release.

I'm also planning to add few new languages with each release.

In case Ace doesn't support required language, it's possible to create language-specific modes: [Ace docs](https://ace.c9.io/#nav=higlighter)

And thank you for the "Other ideas"! 
I've added them on my ToDo list.

**Comment by milikhin** [comment]
[v0.2.8](https://github.com/milikhin/seabass/releases/tag/v0.2.8) adds support for Latex, "Other ideas" merged with "Further improvements" section of readme

**Comment by joaofl** [comment]
Thanks, and congrats for the nice initiative!
