### ISSUE TITLE
QML syntax highlighting support

### ISSUE THREAD

**Issue by tim-sueberkrueb** [milikhin/seabass#8]
First of all, amazing project.
Is there any chance we could get Qt QML syntax highlighting support?
Anyway, keep up the great work!

**Comment by milikhin** [comment]
Thank you for the feedback.

Well, it seems that Ace editor doesn't have built-in support for QML, but I've found [this mode by Parnswir](https://github.com/Parnswir/ace-mode-qml). I'll try it and if everything will be OK, i'll add QML support in next release.

**Comment by tim-sueberkrueb** [comment]
@milikhin awesome!

**Comment by milikhin** [comment]
Added support for _.qml_ and _.qmlproject_ files.
Will be available in 0.2.9 release.
